local-simulation:
  user-workflow:
    workflow-name: "aegis-forensic-analysis"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "../threatDetection/config.json"
    secrets-path: "../../../secrets.yaml"

staging:
  user-workflow:
    workflow-name: "aegis-forensic-analysis"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "../threatDetection/config.json"
    secrets-path: "../../../secrets.yaml"
